class ErrorCodes:
    # JWT Errors
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_MISSING = "TOKEN_MISSING"

    # Flask Errors
    NO_DATA_PROVIDED = "NO_DATA_PROVIDED"
    INVALID_JSON = "INVALID_JSON"
    REQUEST_MUST_BE_JSON = "REQUEST_MUST_BE_JSON"

    # Auth Errors
    INVALID_EMAIL_OR_PASSWORD = "INVALID_EMAIL_OR_PASSWORD"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_CREATION_FAILED = "USER_CREATION_FAILED"
    

    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"